---
title: "Get GMD data - complete workflow"
author: "Heike Sprenger"
date: "November 9, 2015"
output:
  html_document:
    highlight: tango
    number_section: yes
    theme: cerulean
    toc: yes
    toc_float: true
    toc_depth: 4
---

# Load packages and scripts
```{r load workspace, message=FALSE, warning=FALSE}
library(knitr)
library(pander)

# https://github.com/yihui/knitr/commit/470cbbf0111868bb00d1d66693beda326537d789
# https://github.com/yihui/knitr/issues/957
options(knitr.duplicate.label = 'allow')

# set options for pander
panderOptions('table.split.table', 200)

# set options for knitr
opts_chunk$set(fig.width=5, fig.height=5, cache=FALSE, highlight = TRUE, fig.show="asis")
# opts_knit$set(root.dir = '../')
```


# Get Phenotyper metadata ``phenotyper_metadata.Rmd``
```{r child='phenotyper_metadata.Rmd'}
```


# Get crucial GMD data - first steps ``gmd_first_steps.Rmd``
```{r child='gmd_first_steps.Rmd'}
```


# Get GMD raw values ``gmd_raw_values.Rmd``
```{r child='gmd_raw_values.Rmd'}
```


# Get GMD metadata ``gmd_metadata.Rmd``
```{r child='gmd_metadata.Rmd'}
```


# Get GMD analytes information ``gmd_analytes.Rmd``
```{r child='gmd_analytes.Rmd'}
```


# SessionInfo
```{r sessionInfo}
sessionInfo()
```